apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${K8S_NAMESPACE} # <i>
  name: "oci"
spec:
  selector:
    matchLabels:
      app: "oci"
  template:
    metadata:
      labels:
        app: "oci"
    spec:
      serviceAccountName: gcn-service-acct # <ii>
      automountServiceAccountToken: true
      containers:
        - name: "oci"
          image: ${OCI_OS_OKE_IMAGE} # <iii>
          imagePullPolicy: Always # <iv>
          env:
          - name: OCI_OS_NS # <v>
            value: ${OCI_OS_NS}
          - name: OCI_OS_BUCKET_NAME # <v>
            value: ${OCI_OS_BUCKET_NAME}
          - name: MICRONAUT_ENVIRONMENTS # <vi>
            value: "oraclecloud"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
      imagePullSecrets: # <vii>
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  namespace: ${K8S_NAMESPACE} # <i>
  name: "oci"
  annotations: # <ii>
    oci.oraclecloud.com/load-balancer-type: "lb"
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "10"
spec:
  selector:
    app: "oci"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080

